# Network Baseline deployment unit
# Generated by Iltero Template Engine
# Template: technology-aws-modern-stack
# Organization: 25cf5df0-b603-4ea5-9b55-8bfde0b728a9

module "network-baseline" {
  source  = "registry.iltero.io/iltero/network-baseline/aws"
  version = "~> 1.0"

  # CORE CONFIGURATION
  aws_region  = var.aws_region
  environment = var.environment

  # VPC CONFIGURATION
  create_vpc           = var.create_vpc
  enable_dns_hostnames = var.enable_dns_hostnames
  enable_dns_support   = var.enable_dns_support
  vpc_cidr             = var.vpc_cidr
  vpc_id               = var.vpc_id
  vpc_name             = var.vpc_name

  # SUBNET CONFIGURATION
  azs                   = var.azs
  database_subnet_cidrs = var.database_subnet_cidrs
  database_subnet_ids   = var.database_subnet_ids
  database_subnets      = var.database_subnets
  private_subnet_cidrs  = var.private_subnet_cidrs
  private_subnet_ids    = var.private_subnet_ids
  private_subnets       = var.private_subnets
  public_subnet_cidrs   = var.public_subnet_cidrs
  public_subnet_ids     = var.public_subnet_ids
  public_subnets        = var.public_subnets

  # NAT & VPN GATEWAY
  enable_nat_gateway = var.enable_nat_gateway
  enable_vpn_gateway = var.enable_vpn_gateway
  single_nat_gateway = var.single_nat_gateway

  # SECURITY GROUPS
  alb_allowed_cidrs        = var.alb_allowed_cidrs
  app_custom_ingress_rules = var.app_custom_ingress_rules
  bastion_allowed_cidrs    = var.bastion_allowed_cidrs
  create_alb_sg            = var.create_alb_sg
  create_app_sg            = var.create_app_sg
  create_bastion_sg        = var.create_bastion_sg
  create_db_sg             = var.create_db_sg
  db_custom_ingress_rules  = var.db_custom_ingress_rules
  enable_mysql_access      = var.enable_mysql_access
  enable_postgres_access   = var.enable_postgres_access

  # WAF CONFIGURATION
  allowed_ips             = var.allowed_ips
  blocked_domains         = var.blocked_domains
  blocked_ips             = var.blocked_ips
  enable_waf              = var.enable_waf
  enable_waf_logging      = var.enable_waf_logging
  rate_limit_threshold    = var.rate_limit_threshold
  waf_custom_rules        = var.waf_custom_rules
  waf_log_destination_arn = var.waf_log_destination_arn
  waf_name                = var.waf_name
  waf_redacted_fields     = var.waf_redacted_fields
  waf_scope               = var.waf_scope

  # NETWORK FIREWALL
  enable_firewall_logging  = var.enable_firewall_logging
  enable_network_firewall  = var.enable_network_firewall
  firewall_subnet_mappings = var.firewall_subnet_mappings
  network_firewall_name    = var.network_firewall_name
  suricata_rules_capacity  = var.suricata_rules_capacity
  suricata_rules_content   = var.suricata_rules_content

  # NETWORK ACLs
  database_custom_rules          = var.database_custom_rules
  database_dedicated_network_acl = var.database_dedicated_network_acl
  enable_network_acls            = var.enable_network_acls
  private_dedicated_network_acl  = var.private_dedicated_network_acl
  public_dedicated_network_acl   = var.public_dedicated_network_acl

  # VPC FLOW LOGS
  enable_flow_logs           = var.enable_flow_logs
  flow_logs_destination_arn  = var.flow_logs_destination_arn
  flow_logs_destination_type = var.flow_logs_destination_type
  flow_logs_traffic_type     = var.flow_logs_traffic_type
  log_retention_days         = var.log_retention_days

  # OTHER CONFIGURATION
  custom_rule_groups = var.custom_rule_groups

  # Tags (if supported by module)
  tags = var.tags
}

