

# =============================================================================
# Cross-Unit Data Sources - Scaffolding for monitoring-baseline
# =============================================================================
# Generated by Iltero - Customize paths and configuration for your infrastructure
#
# These data sources allow you to reference outputs from other deployment units.
# The state paths use variables so you can configure them in terraform.tfvars.
#
# Template: technology-aws-modern-stack
# =============================================================================


# Reference to security-baseline unit state
# Available outputs depend on what security-baseline actually exports
data "terraform_remote_state" "security_baseline" {
  backend = "s3"

  config = {
    bucket = var.terraform_state_bucket
    key    = "${var.stack_name}/${var.environment}/security-baseline/terraform.tfstate"
    region = var.aws_region
  }
}

# Reference to network-baseline unit state
# Available outputs depend on what network-baseline actually exports
data "terraform_remote_state" "network_baseline" {
  backend = "s3"

  config = {
    bucket = var.terraform_state_bucket
    key    = "${var.stack_name}/${var.environment}/network-baseline/terraform.tfstate"
    region = var.aws_region
  }
}

# =============================================================================
# USAGE EXAMPLES (uncomment and modify as needed):
# =============================================================================
#
# Access security-baseline outputs:
#   data.terraform_remote_state.security_baseline.outputs.<output_name>
#
# Access network-baseline outputs:
#   data.terraform_remote_state.network_baseline.outputs.<output_name>
#
# Check the outputs.tf file of each source unit to see available outputs.
# =============================================================================
