# Monitoring Baseline deployment unit
# Generated by Iltero Template Engine
# Template: technology-aws-modern-stack
# Organization: 25cf5df0-b603-4ea5-9b55-8bfde0b728a9

module "monitoring-baseline" {
  source  = "registry.iltero.io/iltero/monitoring-baseline/aws"
  version = "~> 1.0"

  # CORE CONFIGURATION
  aws_region  = var.aws_region
  environment = var.environment

  # VPC FLOW LOGS
  security_log_retention_days = var.security_log_retention_days

  # CLOUDTRAIL
  cloudtrail_bucket_name            = var.cloudtrail_bucket_name
  cloudtrail_kms_key_id             = var.cloudtrail_kms_key_id
  cloudtrail_name                   = var.cloudtrail_name
  cloudtrail_s3_key_prefix          = var.cloudtrail_s3_key_prefix
  enable_cloudtrail                 = var.enable_cloudtrail
  enable_cloudtrail_cloudwatch_logs = var.enable_cloudtrail_cloudwatch_logs

  # AWS CONFIG
  config_bucket_name                   = var.config_bucket_name
  config_delivery_channel_name         = var.config_delivery_channel_name
  config_delivery_frequency            = var.config_delivery_frequency
  config_include_global_resource_types = var.config_include_global_resource_types
  config_record_all_resource_types     = var.config_record_all_resource_types
  config_recorder_name                 = var.config_recorder_name
  config_resource_types                = var.config_resource_types
  config_role_arn                      = var.config_role_arn
  config_role_name                     = var.config_role_name
  config_s3_key_prefix                 = var.config_s3_key_prefix
  enable_config                        = var.enable_config
  enable_config_rules                  = var.enable_config_rules

  # GUARDDUTY
  create_guardduty_findings_sns          = var.create_guardduty_findings_sns
  create_guardduty_s3_destination        = var.create_guardduty_s3_destination
  enable_guardduty                       = var.enable_guardduty
  enable_guardduty_kubernetes_audit_logs = var.enable_guardduty_kubernetes_audit_logs
  enable_guardduty_malware_protection    = var.enable_guardduty_malware_protection
  enable_guardduty_notifications         = var.enable_guardduty_notifications
  enable_guardduty_s3_logs               = var.enable_guardduty_s3_logs
  guardduty_event_rule_name              = var.guardduty_event_rule_name
  guardduty_finding_kms_key_arn          = var.guardduty_finding_kms_key_arn
  guardduty_finding_publishing_frequency = var.guardduty_finding_publishing_frequency
  guardduty_findings_bucket_name         = var.guardduty_findings_bucket_name
  guardduty_findings_kms_key_arn         = var.guardduty_findings_kms_key_arn
  guardduty_findings_sns_topic_name      = var.guardduty_findings_sns_topic_name
  guardduty_notification_emails          = var.guardduty_notification_emails

  # SECURITY HUB
  create_security_hub_findings_sns      = var.create_security_hub_findings_sns
  enable_default_security_hub_standards = var.enable_default_security_hub_standards
  enable_security_hub                   = var.enable_security_hub
  enable_security_hub_integration       = var.enable_security_hub_integration
  security_hub_event_rule_name          = var.security_hub_event_rule_name
  security_hub_findings_sns_topic_name  = var.security_hub_findings_sns_topic_name

  # CLOUDWATCH
  cloudwatch_logs_kms_key_arn    = var.cloudwatch_logs_kms_key_arn
  cloudwatch_logs_kms_key_id     = var.cloudwatch_logs_kms_key_id
  cloudwatch_logs_retention      = var.cloudwatch_logs_retention
  create_cloudwatch_dashboard    = var.create_cloudwatch_dashboard
  create_security_alarms_sns     = var.create_security_alarms_sns
  enable_cloudwatch              = var.enable_cloudwatch
  enable_security_alarms         = var.enable_security_alarms
  security_alarms_sns_topic_name = var.security_alarms_sns_topic_name
  security_log_group_name        = var.security_log_group_name

  # KMS CONFIGURATION
  kms_deletion_window_in_days = var.kms_deletion_window_in_days

  # NOTIFICATIONS
  alert_emails     = var.alert_emails
  create_sns_topic = var.create_sns_topic

  # OTHER CONFIGURATION
  api_call_volume_threshold                       = var.api_call_volume_threshold
  create_critical_findings_eventbridge_rule       = var.create_critical_findings_eventbridge_rule
  create_security_dashboard                       = var.create_security_dashboard
  enable_aws_foundational_security_best_practices = var.enable_aws_foundational_security_best_practices
  enable_cis_aws_foundations_benchmark            = var.enable_cis_aws_foundations_benchmark
  enable_cis_standard                             = var.enable_cis_standard
  enable_finding_aggregation                      = var.enable_finding_aggregation
  enable_nist_800_53                              = var.enable_nist_800_53
  enable_nist_standard                            = var.enable_nist_standard
  enable_pci_dss                                  = var.enable_pci_dss
  enable_pci_dss_standard                         = var.enable_pci_dss_standard
  failed_login_threshold                          = var.failed_login_threshold
  force_destroy_buckets                           = var.force_destroy_buckets
  monitor_lambda_data_events                      = var.monitor_lambda_data_events
  security_dashboard_name                         = var.security_dashboard_name

  # Tags (if supported by module)
  tags = var.tags
}

