# Provider configuration for network-baseline deployment unit
# Values provided via tfvars per environment
# Generated by Iltero Template Engine

provider "aws" {
  region = var.aws_region

  dynamic "assume_role" {
    for_each = var.assume_role_arn != null ? [1] : []
    content {
      role_arn = var.assume_role_arn
    }
  }

  default_tags {
    tags = {
      Environment = var.environment
      Stack       = var.stack_name
      Unit        = "network-baseline"
      ManagedBy   = "Terraform"
    }
  }
}

