# Security Baseline deployment unit
# Generated by Iltero Template Engine
# Template: technology-aws-modern-stack
# Organization: 25cf5df0-b603-4ea5-9b55-8bfde0b728a9

module "security-baseline" {
  source  = "registry.iltero.io/iltero/security-baseline/aws"
  version = "~> 1.0"

  # CORE CONFIGURATION
  aws_account_id = var.aws_account_id
  aws_region     = var.aws_region
  environment    = var.environment

  # CLOUDTRAIL
  cloudtrail_kms_key_id         = var.cloudtrail_kms_key_id
  cloudtrail_name               = var.cloudtrail_name
  cloudtrail_s3_bucket_name     = var.cloudtrail_s3_bucket_name
  enable_cloudtrail             = var.enable_cloudtrail
  enable_cloudtrail_data_events = var.enable_cloudtrail_data_events

  # AWS CONFIG
  config_delivery_frequency       = var.config_delivery_frequency
  config_excluded_resource_types  = var.config_excluded_resource_types
  config_include_global_resources = var.config_include_global_resources
  config_record_all_resources     = var.config_record_all_resources
  config_s3_bucket_name           = var.config_s3_bucket_name
  config_sns_topic_name           = var.config_sns_topic_name
  enable_config                   = var.enable_config
  enable_config_rules             = var.enable_config_rules

  # GUARDDUTY
  enable_guardduty                       = var.enable_guardduty
  enable_guardduty_eks_protection        = var.enable_guardduty_eks_protection
  enable_guardduty_malware_protection    = var.enable_guardduty_malware_protection
  enable_guardduty_notifications         = var.enable_guardduty_notifications
  enable_guardduty_s3_protection         = var.enable_guardduty_s3_protection
  guardduty_export_findings_to_s3        = var.guardduty_export_findings_to_s3
  guardduty_finding_frequency            = var.guardduty_finding_frequency
  guardduty_notification_severity_levels = var.guardduty_notification_severity_levels

  # SECURITY HUB
  compliance_frameworks                    = var.compliance_frameworks
  enable_security_hub                      = var.enable_security_hub
  enable_securityhub_notifications         = var.enable_securityhub_notifications
  security_hub_enable_standards            = var.security_hub_enable_standards
  securityhub_notification_severity_levels = var.securityhub_notification_severity_levels

  # MACIE
  create_macie_dashboard                   = var.create_macie_dashboard
  enable_macie                             = var.enable_macie
  enable_macie_classification_jobs         = var.enable_macie_classification_jobs
  enable_macie_notifications               = var.enable_macie_notifications
  macie_classification_bucket_names        = var.macie_classification_bucket_names
  macie_classification_schedule_frequency  = var.macie_classification_schedule_frequency
  macie_custom_data_identifiers            = var.macie_custom_data_identifiers
  macie_delegated_admin_account_id         = var.macie_delegated_admin_account_id
  macie_finding_publishing_frequency       = var.macie_finding_publishing_frequency
  macie_kms_key_arn                        = var.macie_kms_key_arn
  macie_master_account_id                  = var.macie_master_account_id
  macie_notification_severity_scores       = var.macie_notification_severity_scores
  macie_results_expiration_days            = var.macie_results_expiration_days
  macie_results_noncurrent_expiration_days = var.macie_results_noncurrent_expiration_days
  macie_results_transition_to_glacier_days = var.macie_results_transition_to_glacier_days
  macie_results_transition_to_ia_days      = var.macie_results_transition_to_ia_days

  # AWS BACKUP
  backup_completion_window             = var.backup_completion_window
  backup_kms_key_arn                   = var.backup_kms_key_arn
  backup_resource_arns                 = var.backup_resource_arns
  backup_start_window                  = var.backup_start_window
  backup_tag_conditions                = var.backup_tag_conditions
  backup_vault_lock_changeable_days    = var.backup_vault_lock_changeable_days
  backup_vault_lock_max_retention_days = var.backup_vault_lock_max_retention_days
  backup_vault_lock_min_retention_days = var.backup_vault_lock_min_retention_days
  backup_vault_name                    = var.backup_vault_name
  create_critical_backup_vault         = var.create_critical_backup_vault
  daily_backup_cold_storage_after      = var.daily_backup_cold_storage_after
  daily_backup_delete_after            = var.daily_backup_delete_after
  daily_backup_schedule                = var.daily_backup_schedule
  enable_backup                        = var.enable_backup
  enable_backup_notifications          = var.enable_backup_notifications
  enable_backup_vault_lock             = var.enable_backup_vault_lock
  enable_daily_backups                 = var.enable_daily_backups
  enable_monthly_backups               = var.enable_monthly_backups
  enable_weekly_backups                = var.enable_weekly_backups
  monthly_backup_cold_storage_after    = var.monthly_backup_cold_storage_after
  monthly_backup_delete_after          = var.monthly_backup_delete_after
  monthly_backup_schedule              = var.monthly_backup_schedule
  weekly_backup_cold_storage_after     = var.weekly_backup_cold_storage_after
  weekly_backup_delete_after           = var.weekly_backup_delete_after
  weekly_backup_schedule               = var.weekly_backup_schedule

  # IAM CONFIGURATION
  enable_iam_analyzer        = var.enable_iam_analyzer
  enable_iam_password_policy = var.enable_iam_password_policy
  iam_password_policy        = var.iam_password_policy

  # KMS CONFIGURATION
  kms_key_arn = var.kms_key_arn

  # NOTIFICATIONS
  enable_analyzer_notifications = var.enable_analyzer_notifications
  notification_email            = var.notification_email

  # OTHER CONFIGURATION
  create_access_analyzer_dashboard = var.create_access_analyzer_dashboard
  create_compliance_dashboard      = var.create_compliance_dashboard
  create_custom_analyzer_role      = var.create_custom_analyzer_role
  enable_auto_archive_rules        = var.enable_auto_archive_rules
  enable_org_analyzer              = var.enable_org_analyzer
  trusted_aws_services             = var.trusted_aws_services
  trusted_external_accounts        = var.trusted_external_accounts

  # Tags (if supported by module)
  tags = var.tags
}

