# Backend configuration for staging
# Unit: security-baseline
# Stack: aws-soc2-non-prod
# Organization: 25cf5df0-b603-4ea5-9b55-8bfde0b728a9
# Generated by Iltero Bootstrap System
#
# Usage: terraform init -backend-config="config/backend/staging.hcl"

# Local backend (for development/testing only)
path = "terraform.tfstate"
